apiVersion: v2
name: url-shortner-app
description: Umbrella Helm chart for the full application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgres-db
    version: 0.1.0
    repository: "file://charts/postgres-db"
  - name: auth-service
    version: 0.1.0
    repository: "file://charts/auth-service"
  - name: business-logic
    version: 0.1.0
    repository: "file://charts/business-logic"
  - name: web-app
    version: 0.1.0
    repository: "file://charts/web-app"
  - name: adminer
    version: 0.1.0
    repository: "file://charts/adminer"
