apiVersion: v1
kind: Service
metadata:
  name: {{ include "business-logic.fullname" . }}
  labels:
    app: {{ include "business-logic.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "business-logic.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
