kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
      - containerPort: 30088
        hostPort: 30088
      - containerPort: 30090
        hostPort: 30090
      - containerPort: 30000
        hostPort: 30000
