apiVersion: apps/v1
kind: Deployment
metadata:
    name: business-logic
spec:
    replicas: 1
    selector:
        matchLabels:
            app: business-logic
    template:
        metadata:
            labels:
                app: business-logic
        spec:
            containers:
                - name: business-logic
                  image: andreimurica/cc-business-logic:latest
                  imagePullPolicy: IfNotPresent

                  ports:
                      - containerPort: 8080

                  env:
                      - name: POSTGRES_HOST
                        value: "postgres-db-service"
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: postgres-db-secret
                                key: postgres-dbname
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: postgres-db-secret
                                key: postgres-user
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-db-secret
                                key: postgres-password
                      - name: SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: postgres-db-secret
                                key: jwt-secret-key
