apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "portainer.fullname" . }}-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: {{ include "portainer.fullname" . }}-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io