apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    app: {{ include "postgres-db.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgres-db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-db.name" . }}
    spec:
      containers:
        - name: postgres-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: postgres-dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage-volume
              mountPath: /var/lib/postgresql/data
              subPath: {{ .Values.persistence.subPath }}
            - name: postgres-init-volume
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: postgres-storage-volume
          persistentVolumeClaim:
            claimName: {{ include "postgres-db.fullname" . }}-pvc
        - name: postgres-init-volume
          configMap:
            name: {{ .Values.initScript.configMapName }}
