apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres-db.fullname" . }}-pvc
  labels:
    app: {{ include "postgres-db.name" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
