apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app: {{ include "postgres-db.name" . }}
type: Opaque
stringData:
  postgres-dbname: {{ .Values.secrets.postgresDB }}
  postgres-user: {{ .Values.secrets.postgresUser }}
  postgres-password: {{ .Values.secrets.postgresPassword }}
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey }}
